### ISSUE TITLE
Calculate total proof of work 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/torba#7]
Calculating the total proof of work is generally a useful metric to return, and necessary to do reorgs trustlessly. The total proof of work is the summation of all the work on the chain , work for each block is defined below: 

https://github.com/lbryio/lbrycrd/blob/e90d7f54cede3c1c5bfc3590351054bdc5a99480/src/chain.cpp#L114

Actually electrum doesn't even have this... I'm not even sure how that works without being exploitable.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by eukreign** [comment]
@kaykurokawa the code you linked to appears to be calculating just for one block, no?

in the lbry implementation of torba ledger the proof of work is calculated here:
https://github.com/lbryio/lbry/blob/ee5be5adc80d4513fbd2fa26881833de3487dd54/lbrynet/wallet/header.py#L48-L78

Is what you're asking about different from that?

**Comment by kaykurokawa** [comment]
Yes, and it basically just gets added to the blockchain's total proof of work like so (nChainWork): 

https://github.com/lbryio/lbrycrd/blob/master/src/main.cpp#L3435

So you have some number that represents the total amount of work that have been put on a chain. The blockchain with most cumulative total work is the correct blockchain. I suppose electrum maybe doesn't bother to calculate this because they figure faking a block is expensive enough? Not sure

For our chain, it would be much cheaper to do an attack where you reorg them to the wrong chain because we have a much lower network hashrate and the difficulty adjustment kicks in much faster on a per block basis.

**Comment by eukreign** [comment]
The reason that electrum (and currently torba) do not do any of this is because it's an SPV wallet, it doesn't get to decide which chain to follow: it only sees what the SPV server makes available.

In order to actually be able to pick chains torba would need to support connecting and following more than one electrumx SPV servers at the same time and then having logic to differentiate and only follow a specific electrumx server when one of them starts following the "wrong" chain.

Long term we want to implement this for sure but I don't know when this will happen.

**Comment by alyssaoc** [comment]
closing from the icebox
